import { Project, Experience, Skill } from './types';

export const projects: Project[] = [
  {
    id: 'predictive-maintenance',
    title: 'Predictive Maintenance Platform',
    description: 'FastAPI + scikit-learn platform that scores equipment failure risk from live sensor readings (vibration, temperature), enabling proactive rather than reactive maintenance. Asset, sensor, prediction, maintenance log, and alert data models built on PostgreSQL/SQLAlchemy support simultaneous monitoring of multiple equipment assets. Includes a threshold-based alerting service with duplicate-alert suppression, an APScheduler background job for automatic periodic evaluation, and a React (Vite) + Recharts + Zustand dashboard giving operations teams real-time visibility into asset health and maintenance analytics. JWT auth with Argon2 password hashing; backend and frontend containerized as independent Docker services.',
    shortDescription: 'ML-powered platform for industrial equipment failure prediction and maintenance scheduling',
    technologies: ['FastAPI', 'scikit-learn', 'PostgreSQL', 'SQLAlchemy', 'React (Vite)', 'Recharts', 'Zustand', 'Docker'],
    featured: true,
    category: 'industrial',
    impact: 'Real-time monitoring across multiple assets, threshold-based alerting with duplicate suppression, fully automated background prediction jobs',
    role: 'Backend Engineer',
    date: '2025 – 2026',
  },
  {
    id: 'payment-gateway',
    title: 'Payment Gateway',
    description: 'Secure end-to-end transaction processing platform handling card and bank-based payments, with idempotent API endpoints for consistency across retries. Webhook handling and signature verification secure asynchronous payment events. Transaction logging, auditing, and reconciliation logic improve financial traceability, and basic fraud/risk validation rules catch invalid or suspicious transactions before processing. Containerized with Docker and deployed with environment-based configuration.',
    shortDescription: 'Secure transaction processing platform',
    technologies: ['Node.js', 'TypeScript', 'Docker'],
    featured: true,
    category: 'fintech',
    impact: 'Reduced failed/duplicated transactions by 90% via webhook + signature verification; reduced manual reconciliation effort by 70%',
    role: 'Backend Engineer',
    date: '2025',
  },
  {
    id: 'mini-loan-decision-engine',
    title: 'Mini Loan Decision Engine',
    description: 'Lightweight, modular rule-based engine that evaluates loan applications by analyzing applicant data and creditworthiness criteria, using weighted score computation across predefined eligibility parameters. Built with TypeScript and Node.js for maintainability, with comprehensive Jest unit tests to keep loan decisions reliable and predictable. Later integrated into a larger loan origination system.',
    shortDescription: 'Rule-based financial decision engine for automating loan approvals',
    technologies: ['TypeScript', 'Node.js', 'Jest'],
    featured: true,
    category: 'fintech',
    role: 'Backend Engineer',
    date: '2025 – Present',
  },
  {
    id: 'district-vibes',
    title: 'District Vibes',
    description: 'Full-stack ticketing platform for a live events brand, enabling event creation, ticket sales, and attendee management through a centralized dashboard. RESTful APIs for event listings, ticket inventory, and order processing support concurrent purchases without overselling. Integrated payment processing for a fully automated sales flow, QR-code-based ticket generation and validation for check-in, and query/API optimizations for peak purchase periods. Deployed to production and used for a live event.',
    shortDescription: 'Event ticketing and sales platform',
    technologies: ['REST APIs', 'Payment Integration', 'QR Codes'],
    featured: false,
    category: 'fullstack',
    impact: 'Reduced check-in time by 60%, cut checkout latency by 35% during peak traffic, ran a live event with zero downtime',
    role: 'Full Stack Engineer',
    date: '2025',
  },
  {
    id: 'redibuy-api',
    title: 'RediBuy API',
    description: 'E-commerce API built with FastAPI, with authentication, cart-based order management, and PayStack-integrated payment and coupon processing. Includes a real-time collaborative recommendation engine caching user browsing/purchase activity, Redis + Celery task queuing for background jobs, and an Nginx reverse proxy in front of a Dockerized deployment on a DigitalOcean droplet.',
    shortDescription: 'E-commerce API with recommendations and background task processing',
    technologies: ['FastAPI', 'Redis', 'Celery', 'PayStack', 'Docker', 'Nginx'],
    featured: false,
    category: 'backend',
    impact: 'Recommendation engine lifted transaction rate by 20%; Redis/Celery task queuing raised application performance by 30%',
    role: 'Backend Engineer',
    date: '2024 – Present',
  },
  {
    id: 'covers-and-spines',
    title: 'Covers and Spines',
    description: 'Bookstore API built with Django and Django REST Framework, covering authentication, book uploads, and payment processing, with clear API documentation written after completion. Containerized with Docker and deployed to Heroku.',
    shortDescription: 'Bookstore API with authentication and payment processing',
    technologies: ['Django', 'Django REST Framework', 'Docker'],
    featured: false,
    category: 'backend',
    role: 'Backend Engineer',
    date: '2024 – Present',
  },
  {
    id: 'virtual-doctor',
    title: 'Virtual Doctor',
    description: 'Web application mimicking real-life hospital check-ins, built with a team of designers and frontend developers. Implemented the backend and endpoints for booking appointments and handling patient information, integrated Google Maps/Places APIs for laboratory and pharmacy locators, and built a symptom-checker endpoint on OpenAI\'s GPT-3.5 Turbo API that matches user-described symptoms against a database of symptoms and diseases to return a possible diagnosis.',
    shortDescription: 'Healthcare app for appointment booking and AI-assisted symptom checking',
    technologies: ['Node.js', 'OpenAI API', 'Google Maps/Places API'],
    featured: false,
    category: 'backend',
    role: 'Backend Engineer',
    date: '2024',
  },
  {
    id: 'shieldforce',
    title: 'ShieldForce',
    description: 'B2B cybersecurity subscription platform. Implemented both frontend and backend for shieldforce.io, integrated third-party APIs from Chargebee, HubSpot, and SendGrid, and deployed both applications on DigitalOcean\'s App Platform.',
    shortDescription: 'B2B cybersecurity subscription platform',
    technologies: ['Node.js', 'Chargebee', 'HubSpot', 'SendGrid', 'DigitalOcean'],
    featured: false,
    category: 'fullstack',
    impact: '40% increase in website performance, 25% decrease in page load time',
    role: 'Software Engineer',
    date: '2023 – 2024',
  },
];

export const experiences: Experience[] = [
  {
    company: 'EPINEC NG',
    title: 'Software Engineer / Web Administrator',
    startDate: '12/2022',
    endDate: '07/2025',
    description: 'Revamped and optimized the company website and built out frontend/backend architecture for shieldforce.io and epinec.us, handling third-party API integrations and production deployment/maintenance.',
    technologies: ['Node.js', 'JavaScript', 'HubSpot API', 'Docker', 'DigitalOcean'],
    achievements: [
      'Eliminated 80+ bugs and cut page load time by 40% on the company website, driving a 25% increase in conversions and a 60% rise in traffic and feedback',
      'Built shieldforce.io front- and backend, improving website performance by 40% and cutting page load time by 25%',
      'Built epinec.us front- and backend, adding CSV export and a HubSpot webhook integration for lead creation',
      'Led the launch of shieldforce.io from the Software Engineering department',
    ],
  },
  {
    company: 'Kafz Luxury Apartments',
    title: 'In-House Developer',
    startDate: '08/2022',
    endDate: '12/2022',
    description: 'Maintained the technical aspects of the company\'s digital presence.',
    technologies: ['Web Development', 'Google Business Suite'],
    achievements: [
      'Increased the company\'s online presence by 100% by building and hosting a landing page and setting up Google Maps/Google Business listings',
    ],
  },
];

export const skills: Skill[] = [
  {
    category: 'Languages & Frameworks',
    items: ['Python', 'Django', 'Django REST Framework', 'FastAPI', 'JavaScript', 'TypeScript', 'Node.js', 'Express', 'React', 'Next.js', 'Go', 'C'],
  },
  {
    category: 'Cloud & DevOps',
    items: ['AWS', 'DigitalOcean', 'Docker', 'Kubernetes', 'GitHub Actions', 'GCP'],
  },
  {
    category: 'Databases',
    items: ['PostgreSQL', 'MySQL', 'MongoDB', 'Prisma', 'Convex'],
  },
];